#!/bin/bash
# Génère des notes de release automatiquement

VERSION=${1:-$(date +%Y.%m.%d)}
PREVIOUS_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")

echo "✨ Génération des notes de release pour la version $VERSION"
echo ""

# Récupérer les commits depuis la dernière version
if [ "$PREVIOUS_TAG" != "v0.0.0" ]; then
    echo "## 📝 Changelog depuis $PREVIOUS_TAG"
    echo ""
    git log --pretty=format:"- %s (%an)" $PREVIOUS_TAG..HEAD --reverse
    echo ""
fi

echo "## 📊 Statistiques du build"
echo ""

# Lire les checksums
if [ -f "output/firmware/checksums.sha256" ]; then
    echo "### Checksums des artefacts"
    echo "\`\`\`"
    grep -v "^#" output/firmware/checksums.sha256 | while IFS='|' read -r file sha256 md5 size; do
        echo "$file: \`$sha256\`"
    done
    echo "\`\`\`"
    echo ""
fi

echo "## 🚀 Comment installer"
echo ""
echo "1. Télécharger la release"
echo "2. Extraire l'archive sur une clé USB formatée en FAT32"
echo "3. Insérer la clé dans le Karotz"
echo "4. Maintenir le bouton arrière enfoncé pendant la mise sous tension"
echo "5. Attendre que la LED devienne verte (installation terminée)"
echo ""
echo "---"
echo "Generated by: Karotz Open Firmware CI/CD"
echo "Date: $(date)"
