#!/bin/bash
# Generate release notes automatically

VERSION=${1:-$(date +%Y.%m.%d)}
PREVIOUS_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")

echo "Release notes for version $VERSION"
echo ""

if [ "$PREVIOUS_TAG" != "v0.0.0" ]; then
    echo "Changelog since $PREVIOUS_TAG"
    echo ""
    git log --pretty=format:"- %s (%an)" "$PREVIOUS_TAG"..HEAD --reverse
    echo ""
fi

echo "Build statistics"
echo ""

if [ -f "output/firmware/checksums.sha256" ]; then
    echo "Artifact checksums"
    echo "==="
    cat output/firmware/checksums.sha256
    echo "==="
    echo ""
fi

echo "How to install"
echo "1. Download release"
echo "2. Extract to FAT32 USB"
echo "3. Insert into Karotz"
echo "4. Hold back button while powering on"
echo "5. Wait for green LED"
echo ""
echo "Generated by Karotz CI/CD"
echo "Date: $(date)"

